name: Create File Based on Input

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "John Doe"
      message:
        description: "Enter your message"
        required: true

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create file based on input
        run: |
          echo "Name: ${{ github.event.inputs.name }}" > output.txt
          echo "Message: ${{ github.event.inputs.message }}" >> output.txt

      - name: Commit and push the file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output.txt
          git commit -m "Added output.txt based on input"
          git push
